### ISSUE TITLE
Remove the "set" cast in the setup.py

### ISSUE THREAD

**Issue by clemfromspace** [limpyd/redis-limpyd#112]
The `set` cast on this line (https://github.com/limpyd/redis-limpyd/blob/master/setup.py#L23) in the setup.py file make this package uninstallable when `setuptools` version is >= 38.2.3

See also: 
- https://github.com/pypa/setuptools/commit/f012485e4767f3be81493c93ad534a02c6f14f14#diff-0f33d7d69d9f143736a252a75373261bR169
- https://github.com/pypa/setuptools/issues/458#issuecomment-346944831

And also, hello @twidi :)

This is also the case in the related `redis-limpyd-extensions` package https://github.com/limpyd/redis-limpyd-extensions

**Comment by twidi** [comment]
In fact we should keep the set (to remove duplicates) and then convert it to a list.

But mainly, this setup.py should be should be rewritten from the ground up as explained (in french) here: https://twidi.github.io/python-packaging-talk/fr  / http://pyvideo.org/pycon-fr-2017/les-aventuriers-du-packaging-perdu.html

But this will be for another time.

The important thing is that you just said to me that all of my packages using this way of managing dependencies are broken? I am sad, and it'w the worse time in two years for me, as I work 7/7 :(

**Comment by clemfromspace** [comment]
Yeah, we got this nice surprise yesterday on our main package since the  `mkvirtualenv` install the latest version of `setuptools` by default...
We fixed it on our main package, but there is some dependencies (limpyd and others maybe) who still use the `set`.
So no other choices to downgrade `setuptools` after creating the virtualenv for the moment.

**Comment by twidi** [comment]
I think this will also break the next deployment of Isshub. Thanks for letting me know, better before deploying a fix in a rush than "oh f*** what's going on!!?!??!?!?!?" ;)

**Comment by twidi** [comment]
Fixed in #113 and upcoming version 1.0
