### ISSUE TITLE
[idea] Populate index from a function

### ISSUE THREAD

**Issue by yohanboniface** [limpyd/redis-limpyd#16]
For example, you have a count field in some model.
You know that you will need to retrieve instances where count is lower than say 0.
It could be convenient to be able to do something like:

``` python
def negative_count(inst):
    return int(inst.count.hget() < 0)

class MyModel(model.RedisModel):

    count = fields.HashableField(index="negative_count")
```

And then, each time the field is "modified", the function is called, and the index populated if necessary.
And to use this index, we could imagine something like:

``` python
MyModel.collection(negative_count=True)
```

Just an idea...

**Comment by twidi** [comment]
This can be closed now that powerful indexes are available since version 1.0
