### ISSUE TITLE
Feature Req: Allow setting expires for object

### ISSUE THREAD

**Issue by niteshn** [limpyd/redis-limpyd#57]
Redis allows setting expiry time for keys. It would be really great if limpyd could allow setting expiry time for objects too. This could be applicable for Relational objects too.  

Just a suggestion, might be useful for a lot of cases.

**Comment by twidi** [comment]
As we manage fields independently one from each other, is not possible. Also as the expiry is done in redis (there is no benefit to do it ourselves), we cannot be informed when a key is expired and update the key accordingly.
