### ISSUE TITLE
Reconsider Metaclasses

### ISSUE THREAD

**Issue by yohanboniface** [limpyd/redis-limpyd#62]
We have two metaclasses, `MetaRedisProxy` and `MetaRedisModel`.

Both are becoming quite complex, and are instrusive when using mixins, so maybe a little cleaning, refactoring is needed.

**Comment by twidi** [comment]
`limpyd` evolved and as the only real maintainer, I close this issue as a "wontfix"

If you really want this... you can still propose a PR ;)
